apiVersion: apps/v1
kind: Deployment
metadata:
  name: return
  labels:
    app: return
spec:
  replicas: 5
  selector:
    matchLabels:
      app: return
  template:
    metadata:
      labels:
        app: return
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: return
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser15-return:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: '/returns'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/returns'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
